export const URLJSON = 'https://jsonplaceholder.typicode.com/'
export const COMMENTS = 'comments'
export const POSTS = 'posts'
export const USERS = 'users'
export const PUT = 'PUT'
export const POST = 'POST'
export const DELETE = 'DELETE'